### ISSUE TITLE
Create own plugins

### ISSUE THREAD

**Issue by zorrobyte** [rockstor/rockon-registry#1]
Greetings!

I'm a sysadmin who uses Docker often and I would like to create my own Rock-ons or at least run my own containers. Without hacking the core code, is there/will there be configs to set our own docker repos or use the Docker Hub for images?

**Comment by phillxnet** [comment]
Hello @zorrobyte I've just addressed a very similar question on the forum so I hope you don't mind if I link to that as I hope it has some relevant information.
http://forum.rockstor.com/t/where-to-start-dev-on-new-rockstor-rock-ons-i-do-see-that-docker-is-what-you-are-using-to-package-and-manage/828/2
I know the docker hub images element is an up-voted feature request over at:- http://forum.rockstor.com/t/next-phase-of-rock-on-framework-improvements/417
But I think we are just going to have to see how things go with the current re-write / re-working of the Docker based Rock-ons system.

**Comment by zorrobyte** [comment]
Howdy! Thank you for taking the time to respond! I'll read through the forum post regarding this.

I did find the documentation on setting up a dev environment with Rockstor and PRs, the current implementation of rockon_json.py seems simple enough. I may have a crack at attempting to add Sickrage & Couchpotato images. If all tests well, I'd be happy to submit a PR, even if a rework is on the way - could be a stopgap until then.

BTRFS sounds awesome, I'm rebuilding my Xpenology box since Synology keeps adding malicious code in to kill off the 3rd party implementation. The underlying tech when it comes to rebalancing pools and changing RAID levels made the decision for me to choose this over Freenas and others. Keep up the good work!

**Comment by phillxnet** [comment]
@zorrobyte Things have changed a tad now and wanted to note here for you that there is now a pretty good README.md https://github.com/rockstor/rockon-registry/blob/master/README.md in this very repo on contributing / making your own rock-ons as recent improvements mean that it's just dropping a json file per Rock-on in your own instance of Rockstor and it shows up in the UI as an installable Rock-on.
Cheers for the info re Synology, I didn't know that.
Please consider joining the Rockstor forum as there is quite a bit of discussion re NAS solutions etc these days. http://forum.rockstor.com/

**Comment by phillxnet** [comment]
Closing as fixed by local repo possibility as per last comment here and README.md content. There are not plans for a generic installer from docke hub. We have also now had sickrage and couchpotato Rock-ons for some time.
