### ISSUE TITLE
Rockstor hangs after creating /opt/rockstor/rockons-metastore

### ISSUE THREAD

**Issue by HTPC-Schrauber** [rockstor/rockon-registry#10]
Hi,

I was looking to add my own rockon.

But when I create /opt/rockstor/rockons-metastore directory my box hangs on next reboot. The boot process does never finish. There are no information on screen.

It does not matter, if the created directory is empty or if there is a json in it.

I tried this with last stable (3.8-11) and also with testing updates. Both with the same result.

Regards

**Comment by HTPC-Schrauber** [comment]
OK, reinstalled all.
This time I did it step by step:
- installation
- reboot
- create rockons-metastore directoy
- reboot
- create share for rockons
- reboot
- configure and activate rockon service
- reboot
- refreshed rockons

Now it seems to work without hanging at boot.

**Comment by phillxnet** [comment]
@HTPC-Schrauber Just to say I'm closing this issue as a backlog tidy-up. We haven't had repeat confirmation and it now relates to very old code.
Thanks for the issue and apologies that it got no responses.
