### ISSUE TITLE
Ombi not in list

### ISSUE THREAD

**Issue by alazare619** [rockstor/rockon-registry#108]
@schakrava  appears ombi is not in the list. I've hit update a few times to no luck. Removed the Rockon-Root-Share still no bueno. Had a few others verify this too. No luck Ombi still isn't propagating.

**Comment by phillxnet** [comment]
@alazare619 Thanks for reporting this. This is strange. I can confirm here also. From a quick look it seems like the only Rock-on not showing up in UI from the canonical list in:
https://github.com/rockstor/rockon-registry/blob/master/root.json
Is that your experience also?
It was added to root.json 16 days ago in the following commit:
https://github.com/rockstor/rockon-registry/commit/81189ed02715f07670c5e41396873c3ce81e9106

**Comment by alazare619** [comment]
yes, I have 44 available rockons to choose from. plus 4 I have installed already which is 48. There is 49 in the root.json so it appears ombi is the only one missing.
