### ISSUE TITLE
rockons (plex) reset their config on add/remove volume changes

### ISSUE THREAD

**Issue by coleberhorst** [rockstor/rockon-registry#111]
This is particularly noticeable with plex. The config wipes on any add volume action. Is this an intended action or something that is able to be stopped?

**Comment by phillxnet** [comment]
@coleberhorst I think I know what you mean but could you sketch out the steps you took to reproduce this and the difference between expected/desired and observed behaviour.
Thanks.

**Comment by coleberhorst** [comment]
Sure, wrote this a little late after a day of programming xD

1: Install plex with example volumes "plex-config" as /config and a share "movies" as /data.
2: Configure plex as desired with plex server name etc. Plex starts with a setup wizard.
3: Stop plex and use add storage support to add a share "tv" as /tv.
4: Start plex again with new volume, plex immediately loads the setup wizard and plex has reset your config to a fresh configuration.

**Comment by greggiceton** [comment]
Hi.  I just wanted to let you know that I have just experienced this problem, so its still on going.
