### ISSUE TITLE
btsync rockon should be replace by resilio/sync

### ISSUE THREAD

**Issue by jybleau** [rockstor/rockon-registry#117]
bittorrent/sync docker image has been deprecated and replaced by resilio/sync
https://hub.docker.com/r/resilio/sync/

Deprecated image stops at version 2.3.8 which causes licences issues if all your other peers are on 2.4 using latest Resilio licence model.

Can we expect an upgrade soon? Does changing the Rockon's name and image will cause upgrade problems?

Thanks

**Comment by magicalyak** [comment]
It's probably better to make a new rockon and just either move or reuse the share from the previous one.  It's a hard sell to update the entire rockon since some people may have a need for the older version.  Did you want to take a crack at making a new rockon and submitting a PR request?

**Comment by jybleau** [comment]
Good idea. I'll do a PR.
