### ISSUE TITLE
Addon UNMS

### ISSUE THREAD

**Issue by skynett81** [rockstor/rockon-registry#132]
can you make an addon for UNMS its an addition to Unifi controller

Ubiquiti Network Management System (beta)
Manage all of your EdgeMAX®, EdgeSwitch®, airMAX® and UFiber devices.

Centralized devices configuration, backups and mass FW upgrade
Performance charts with real-time graphs
Outage notifications and custom alerts
Map of your network sites and endpoints
https://github.com/Ubiquiti-App/UNMS

**Comment by phillxnet** [comment]
@skynett81 Thanks for accommodating the move of this issue form rockstor-core.
Linking to your forum post on the same:
https://forum.rockstor.com/t/rocks-ons-addon-unms/3927

**Comment by alazare619** [comment]
I'll see what I can whip up over thanksgiving weekend.

**Comment by alazare619** [comment]
adding notes for future me to reference this weekend after lots of turkey and food comma...

Install script references git repo latest version file then pulls the tar file in the gitrepo with another installscript...second installscript pulls image from docker hub and passes through the following global variables...

`VERSION="latest" PROD="true" DEMO="false" NODE_ENV="" USE_LOCAL_IMAGES="false" DOCKER_IMAGE="ubnt/unms" DOCKER_USERNAME="" DOCKER_PASSWORD="" HTTP_PORT="80" HTTPS_PORT="443" WS_PORT="" PROXY_HTTPS_PORT="" PROXY_WS_PORT="" BEHIND_REVERSE_PROXY="false" SSL_CERT_DIR="" SSL_CERT="" SSL_CERT_KEY="" SSL_CERT_CA="" HOST_TAG="" UNATTENDED="false" NO_AUTO_UPDATE="false" BRANCH="master" SUBNET="" NO_FIRMWARES="false"`

**Comment by alazare619** [comment]
https://github.com/Ubiquiti-App/UNMS/wiki/Manual-installation-using-Docker-Compose

still working on this time has been limited due to holidays wiki has been added

**Comment by alazare619** [comment]
https://github.com/rockstor/rockon-registry/pull/142

**Comment by tyukh** [comment]
> I have recently comment on the linked pull request for this issue. Would be nice to see this put to bed.

Maybe someone try .json-fy that image https://github.com/Nico640/docker-unms
I'm not in game, cause successfully used UNMS 'just run me' installer on Leap 15.1 with Rockstor-Testing as standalone service without Rockstor integration.

**Comment by phillxnet** [comment]
Closing as per linked pull requests last comments.
