### ISSUE TITLE
Created a crashplan pro rockon

### ISSUE THREAD

**Issue by wiza** [rockstor/rockon-registry#146]
Hi,

If anyone else have crashplan pro account, can you test: https://gist.github.com/wiza/bb0a9c76356315422530eae6d63139d5

Uses docker from https://hub.docker.com/r/jlesage/crashplan-pro/ (not mine)

**Comment by phillxnet** [comment]
@wiza Any progress on this Rock-on? Are you still using it for example? In which case I would like to encourage you to create a pull request with it's latest version. That way it can be reviewed and hopefully merged.

**Comment by wiza** [comment]
I’ll do a proper pull request in couple of days when I have time. I do use it. Missing reinstall button in rockstor for quicker updates (need to shutdown, delete and install). For example if rockon has not changed it wouldn’t need to ask options again.

**Comment by FroggyFlox** [comment]
Thanks in advance for your future PR.
I simply wanted to share my two cents on your comment on a "re-install" button. This is actually something I thought about and wouldn't ask for too much on the coding side so I personally be up for it.
If you don't mind, you can create a dedicated issue for it on the `rockstore-core` repository and put more details on what you have in mind (if applicable).

Cheers,

**Comment by wiza** [comment]
There is now a pull request #181.

**Comment by wiza** [comment]
And issue #2022 :)

**Comment by wiza** [comment]
Don’t use it anymore after changes in terms.

**Comment by phillxnet** [comment]
@wiza Could you clarify what's happened in their "changes in terms" that has lead you to close your pull request a few days ago and this issue. I know you mentioned config files in the pr but what does this mean in the context of an allocated share?
Thanks.

**Comment by wiza** [comment]
Those are here: https://support.code42.com/CrashPlan/6/Troubleshooting/What_is_not_backing_up. 

It does allow backing up etc on Linux but it’s severely restricts it’s use as a crash planning tool. My biggest problem was exclusion of sparseimage as I want offsite backups of my mac.

**Comment by phillxnet** [comment]
@wiza Thanks for the info. You could ask on our forum for what others have / are using for their Macs.

**Comment by wiza** [comment]
Macs are backing up to rockstor with time machine. It was just offsite backup of rockstor I was using crashplan for. I’m probably just going to use some pi+big hd and rsync (or something better) there daily.
