### ISSUE TITLE
BTSync Docker image non-existent

### ISSUE THREAD

**Issue by peterdenhaan** [rockstor/rockon-registry#15]
I just unsuccessfully tried to install the BTSync rock-on. Repeatedly.

In `supervisord_ztask-daemon_stderr.log` I found this:
```
ERROR:storageadmin.views.rockon_helpers:Error running a command. cmd = ['/usr/bin/docker', 'run', '--log-driver=syslog', '-d', '--restart=unless-stopped', '--name', 'btsync', '-v', '/mnt2/sync:/data', '-p', '8888:8888/tcp', '-p', '3369:3369/tcp', '-p', '3369:3369/udp', 'aostanin/btsync']. rc = 1. stdout = ['']. stderr = ["Unable to find image 'aostanin/btsync:latest' locally", 'Pulling repository docker.io/aostanin/btsync', 'Error: image aostanin/btsync:latest not found', '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 125, in install
    globals().get('%s_install' % rockon.name.lower(), generic_install)(rockon)
```
And so on. The `btsync` image can't be located on the Docker hub. Indeed, on [aostanin's repository](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=aostanin&starCount=0) there is no longer a `btsync` image. Has he pulled it? If so, we'll need an alternative - and perhaps rethink Rockstor's dependency on third parties who might pull their images at the drop of a hat.

Which is not a quibble. Thanks for the great job you're doing, guys.

**Comment by peterdenhaan** [comment]
I noticed two pull request patching in the `crewjam/btsync` image. I could not get it to work, at least not as a drop-in for `aostanin/btsync`: it does not appear to pick up the container's volumes, but rather expects it to be spoonfed a `VOLUME_NAME` environment variable. I seriously doubt whether it'd support adding more volumes. I can't find documentation for it on the hub or the crewjam website. I wonder if we should really be relying on this.

I've also unsuccessfully messed about with `ctlc/btsync`, which is another popular one; can't connect to the web UI for reasons I didn't yet spend the time to figure out.

It's getting tempting to roll my own `btsync` image at this point. Should you decide that there is mileage in maintaining Rockstor-controlled docker images in cases where there is no stable 'official' image, I might be able to help. I have a reasonable level of Docker experience.

**Comment by peterdenhaan** [comment]
Well, that turned out to be a bit of a no-brainer after all. I did not realise that there is in fact [an official `bittorrent/sync` image](https://hub.docker.com/r/bittorrent/sync/) as of [last September](https://blog.getsync.com/2015/09/16/official-bittorrent-sync-docker-recipe/). It works, and looks like the obvious one to use.

**Comment by phillxnet** [comment]
@peterdenhaan Thanks for your efforts on this and your offer to help as a docker image maintainer. I agree that official images are definitely the way to go for sure but as you say they aren't always available. This is one for @schakrava I'm afraid as my docker knowledge / experience is currently a bit weak.

I see @henfri has a pr which has switched to crewjam/btsync on the basis of most downloads. I favour official though myself. Maybe if you open a pr with a working tested official image based rock-on the two could be evaluated by @schakrava on the next merge round. in this repo. Not sure of the etiquette here really.

**Comment by schakrava** [comment]
Hello @peterdenhaan , you are on the right track. I've been in communication with Bittorrent company to get the official image. The latest is that they want us to wait until 2.3.4 is released, which apparently is coming very soon. But in the meantime, if you want to open a pull request with the current version(2.3.2) of the official image, I'd be thrilled. It will give everyone an opportunity to test as well.

**Comment by henfri** [comment]
@phillxnet , @schakrava 
There is a open PR already with the official Image from me: 
https://github.com/rockstor/rockon-registry/pull/14

I don't know how to test it though, as there is then a conflict with the existing rock on.

**Comment by schakrava** [comment]
I missed it because it has other Rock-ons also with it. May I request you to open a new pull request just for BTSync? In general, it's a good practice to separate multiple Rock-ons into their own pull requests. I'll test it and let you know about conflicts.

**Comment by henfri** [comment]
Hello Suman,

I don't know how to separate this into several pull requests&unfortunately can't work on this this month.
I'll promise to improve for the future.

Nevertheless, https://github.com/rockstor/rockstor-core/issues/1205 is relevant, as I think it would be useful if it would be easy to test or modify also a stock-Rock-On.

Greetings,
Hendrik

**Comment by schakrava** [comment]
No problem. The way to do would be to open a new pull request per Rock-on. We can then ignore/close this pull request.

**Comment by henfri** [comment]
But I can not create a pull-request for a file only.
Thus, I would have to re clone the rock-on registry and then add one rock-on and then create a PR, add the next, create a PR, .. right?

**Comment by jybleau** [comment]
@henfri 
not sure if I can help... 

I think you can just push an updated version of the btsync file in your [patch-1](https://github.com/henfri/rockon-registry/tree/patch-1) branch and then create a new pull request from that branch?

Is that possible?

**Comment by phillxnet** [comment]
@peterdenhaan and @henfri Just linking this issue to a recent forum thread so we can tie the two together and update the forum on development with this one.
https://forum.rockstor.com/t/btsync-install-problem/1280

**Comment by jybleau** [comment]
Seems to be working fine now.
Thank you @schakrava for merging @henfri 's [PR 14](https://github.com/rockstor/rockon-registry/pull/14)

**Comment by peterdenhaan** [comment]
It's working. Thanks!
