### ISSUE TITLE
COPS Rockon incorrectly configures /movies

### ISSUE THREAD

**Issue by lgchris** [rockstor/rockon-registry#165]
https://github.com/rockstor/rockon-registry/blob/master/cops.json#L21

^ Here we're setting up for books at the /movies path. COPS configuration in the image is looking for books at the /books path. This blocks COPS from running properly. 

Recommend updating the line to /books instead of /movies. I'm unable to try it / create a pull from my current environment.

**Comment by phillxnet** [comment]
@lgchris Nice find and thank for opening this issue.  Hopefully someone will pick this one up shortly.

**Comment by FroggyFlox** [comment]
Hi @lgchris , I just created a PR with the changes you recommended. Feel free to test and provide feedback on the corresponding PR: #167
