### ISSUE TITLE
missing root.json entries

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#171]
We currently have a number of missing root.json entries which results in a Web-UI 'no show' for otherwise merged rock-on json files.

Synchronise root.json content with current Rock-on json definition files.

**Comment by phillxnet** [comment]
To ease the task of ensuring we have synchronisation between json files and the root.json the latter was previously arranged alphabetically. This arrangement has since fallen into disrepair. I intend that this issue be used to also re-address the alphabetical arrangement of root.json's content so ease further management of it's content.

To date among the missing we have:
```
...
    "YouTrack": "youtrack.json",
    "Zabbix-XXL": "zabbix-xxl.json",
...
```
However I am due to merge a number of other Rock-on pull requests very shortly that are missing their respective root.json entries so will also use this issue to add the then newly missing additional entries.

**Comment by FroggyFlox** [comment]
Thanks for bringing this up @phillxnet !
That's something I noticed a little while ago and started paying attention to for some pending PR but somehow never took upon fixing for existing Rock-ons. Let me know if you'd like me to take care of it.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for the generous offer; yes it's been bugging me for a bit now but as I'm due to merge a load of the pending pr's (at least those with reviews / confirmation of working) I might as well use this issue to do the associated additional entries / tidy up. I've already done the sort locally using the following rather fine PyCharm plugin:

https://plugins.jetbrains.com/plugin/2162-string-manipulation

![string-manipulation-plugin-sort](https://user-images.githubusercontent.com/2521585/52148291-1e16ba80-2661-11e9-844e-70e14cbeeaa5.png)

![string-manipulation-plugin](https://user-images.githubusercontent.com/2521585/52148304-27a02280-2661-11e9-948f-4e5ac0777f44.png)

Worked like a charm.

Will add the other soon to be required entries under this pr once I've done a fresh Rock-ons pr merge stint; we are certainly well over due for one.

I see you have reviewed quite a few already and put some in yourself so thanks for you efforts on that. I'll merge what I can very soon and we can take it from there.

To anyone wishing to review any of our now shamefully large Rock-on pr backlog; your efforts would be much appreciated.

Please see: https://forum.rockstor.com/t/how-to-test-a-rock-on-pull-request/5224/2
for how to test any pending Rock-on pull request.

Thanks again @FroggyFlox and I do what I can with the backlog hopefully tomorrow.

**Comment by FroggyFlox** [comment]
Sounds good, and thanks again for taking care of this!

In order to help reducing this problem in the future, what do you think about adding instructions on how to add any new JSON file to the `root.json` in a relevant section of the README file? Maybe that one:
https://github.com/rockstor/rockon-registry#steps-to-contribute-a-rock-on-with-a-pull-request

We could even also add the same instructions to the Rockstor's doc (http://rockstor.com/docs/contribute_rockons.html#contributing-to-rockstor-rock-ons) and your forum wiki post...

**Comment by phillxnet** [comment]
Changes to existing entries:

As per "Update Emby Rockon" #161
"EmbyServer": to "Emby server":
