### ISSUE TITLE
use new official pi-hole image

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#176]
Our current pi-hole Rock-on uses the now outdated diginc/pi-hole image.

As per quote from: https://hub.docker.com/r/diginc/pi-hole/ (updated 6 month ago)
"We've moved! To get the latest updated Pi-hole v4.0 please use pihole/pihole:"
we should move to using the new updated image / location.
https://hub.docker.com/r/pihole/pihole/ (updated 2 days ago)

**Comment by FroggyFlox** [comment]
Here's a quick link to the corresponding pending PR #156 (its title isn't that obvious).
I'll try to make a proper Github review of this PR as soon as possible, sorry for the delay.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks, knew I'd seen work on this somewhere.
Looks like we need to reduce our backlog still further.
Work in progress.

Now they are linked we can have that pr close this issue. Maybe requesting a title edit on the linked pr would also help things along.
Thanks to @laxdog for the original pr and @FroggyFlox, and @magicalyak, and @haioken for earlier  reviews.
Lets leave this open for that pr as a 'more obviously titled' link to the the ongoing work.

**Comment by noorbertt** [comment]
any up about a pihole/pihole repo?

**Comment by phillxnet** [comment]
@noorbertt Thanks for the interest. We do have a refreshed pull request by @magicalyak on this move to the newer pi-hole docker image, plus some additional dns changes, linking for context:

"added dns options for pi-hole rockon" #178

and this newer pull request is simply awaiting @magicalyak's response to @FroggyFlox's suggestions.

Upon that being resolved I can merge the latter pr and consequently close this issue and the duplicate 'origin' pr of #156.

**Comment by phillxnet** [comment]
Closing as fixed by now merged #178
