### ISSUE TITLE
Emby /media not usable in emby

### ISSUE THREAD

**Issue by rkunschke** [rockstor/rockon-registry#179]
I try to add the mounted /media/music folder too the Library. The Error says the folder is not in the data-system. I checked the id/gid of the folder and used the right ids on install so thats not the problem.

**Comment by phillxnet** [comment]
@rkunschke Thanks for the report. But I think the best place for this question / query is on our forum, at least initially. There should be others who have experience with this Rock-on that can hopefully chip in on that the problem might be.
Forum can be found here: https://forum.rockstor.com/
