### ISSUE TITLE
[New rock-on] Nginx Proxy Manager

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#180]
I just came across a project that seems like a very good candidate for Rockstor: 
Nginx Proxy Manager: [https://nginxproxymanager.jc21.com](https://nginxproxymanager.jc21.com)

As per its Github page:
> This project comes as a pre-built docker image that enables you to easily forward to your websites running at home or otherwise, including free SSL, without having to know too much about Nginx or Letsencrypt.

[https://github.com/jc21/nginx-proxy-manager](https://github.com/jc21/nginx-proxy-manager)

This seems to provide a user-friendly web-interface to creating and managing Nginx to easily reverse-proxy apps on a server with easy SSL-setup (built-in Let's Encrypt, or own SSL).
The project seems relatively active.

I'm opening this issue to remind me of having a better look at it and see if a Rock-on can easily be made for it. 
Does anyone have experience and feedback on this project?

**Comment by magicalyak** [comment]
You could also change the nginx.conf on the system itself.  I use nginx-plus personally on the system (I work for them is why).  Looks like a good candidate though.

**Comment by FroggyFlox** [comment]
> You could also change the nginx.conf on the system itself. I use nginx-plus personally on the system (I work for them is why). Looks like a good candidate though.

Thanks for the feedback! From what I can remember this project's setup seemed to be a little involved, but your input supports me in the idea that this project might be worth the effort of adapting it into a rock-on. Ultimately, my goal would be to make it easy for a user not familiar with a reverse-proxy to use one to serve any service ran in a rock-on as (s)he desires. This is why having a friendly GUI to change any `*.conf` file needed caught my interest here.

Thanks again!

**Comment by DarkYamik** [comment]
Hello guys!

I am currently working on the implementation of Nginx Proxy Manager to Rockstor. Right now I managed to make it work directly via docker-compose but I think that it will be a nice Rockon.

I'll keep you posted!

**Comment by DarkYamik** [comment]
Hello again!

I already have the rockon up and running!

I've just created the pull request in order to review it https://github.com/rockstor/rockon-registry/pull/211

For now is working fine in my Rockstor appliance

**Comment by FroggyFlox** [comment]
@DarkYamik , @phillxnet , thanks again for taking care of this one.
I believe we can now close this issue ;).

Cheers,

**Comment by FroggyFlox** [comment]
Closing as fixed by #211
