### ISSUE TITLE
[Rock-on Update] YouTrack rock-on is out-of-date and not based on official image

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#201]
The current image used by the [YouTrack](https://www.jetbrains.com/youtrack/) rock-on is using a non-official image hardcoded to use the 2018.2.42133 version. As of today, it also has been updated a year ago.

Notably, an [official image supported by JetBrains](https://hub.docker.com/r/jetbrains/youtrack) is available:
- updated 3 days ago
- uses 2019.2.58831 version

It would thus seem preferable to replace the current rock-on with a new one based on the official image.

**Comment by phillxnet** [comment]
@FroggyFlox Agreed.

**Comment by FroggyFlox** [comment]
I have now tested the official YouTrack image and it works well. A few things to note:

- no drop-in upgrade from the older version used in our current rock-on is possible, but a clear interface exists for backup from the old instance and restore into the new one.
- a dedicated user with a particular UID needs to be created first, but all of it can be done from within Rockstor UI.

I'll thus proceed with finalizing this rock-on and then submit the appropriate PR when I get the chance.
