### ISSUE TITLE
Add RockOn for Postgresql version 9.x and up

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#216]
Create a RockOn json file that allows installation of Postgresql databases with versions 9.x and up. This would include the ability to declare the version required, a Super User/Password combination and an access port. The port is relevant to not interfere with the port set up that RockStor is already using (default port 5432).

**Comment by phillxnet** [comment]
@Hooverdan96 I've edited your linked pull request to close this issue. I know we have the outstanding:

> with versions 9.x and up.

element here that hasn't been addressed but we do have your:

"Ability to specify image tag (for docker pull command) interactively" #218

issue that addresses head on. Thanks again for your efforts at improving our Rock-on range and future capability.
