### ISSUE TITLE
Discourse addon references obsolete/unavailable container

### ISSUE THREAD

**Issue by mcbridematt** [rockstor/rockon-registry#228]
In the course of identifying Rockon's that do not support arm64 (see https://github.com/rockstor/rockstor-core/issues/2191 ), I found that the Discourse addon refers to an obsolete image:

```
"discourse": {
		"image": "discourse/discourse",
```

No image tag is specified in the Rockon so Docker would try to use discourse/discourse:latest which no longer exists.

The image referenced ( https://hub.docker.com/r/discourse/discourse ) has been replaced with https://hub.docker.com/r/discourse/base/ which specifies a "launcher tool" should be used to start it.

**Comment by phillxnet** [comment]
@mcbridematt Thanks for this. Linking to a related issue in rockstor-core indicating the launcher tool issue and our need to 'special case' this Rock-on:

https://github.com/rockstor/rockstor-core/issues/2033

We also have it's linked issue in this repo here:
https://github.com/rockstor/rockon-registry/issues/185

So this issue looks like a duplicate of #185 above. Could you add your findings that are in addition to that issue there so we can close this as a duplicate and have only one to track. But given the work involved and the 'special treatment' it may be better in the mean time to just remove this Rock-on until we have the input to make this so.

Thanks for indicating this and do please pop you given details onto that original issue so we can build up a single point of info around a single issue.

Cheers.

**Comment by mcbridematt** [comment]
Is indeed a duplicate of #185 - apologies.
This was originally going to be an 'omnibus' issue with other containers that have been removed from Docker Hub but it turns out Discourse was the only one once tags were considered.
