### ISSUE TITLE
Add Minio Rock-on

### ISSUE THREAD

**Issue by MikeMcPherson** [rockstor/rockon-registry#231]
Minio is an open source, S3-compatible object storage server.  Many systems and services support S3 as a back-end data store.  

This Minio Rock-on uses the official Minio Docker image to implement a single Minio instance with a single Rockstor share for object storage.  I believe this configuration will be suitable for use on a private network, for personal backup on a home network, for example.  

If connections between the client and the Minio server traverse a network lacking physical security, consider either using a VPN for encryption or putting Minio behind a reverse proxy for encryption.  Implementing native encryption in the Minio Rock-on, although possible, would require the user to do on-going certificate management in addition to the Minio Rock-on installation.  This would violate the '"all-in-one" user experience' guideline in "Contributing a Rock-on."

**Comment by MikeMcPherson** [comment]
What's the best way to let people know that this Rock-on will only work on a version of Rockstor with Docker command argument support (looks like 3.9.2-39 or later to me)?  It will not work with the ISO; I actually butted my head against that one on the dev server I created to test this Rock-on.  A non-developer will never figure it out and will just give up.  Any chance of updating the ISO to a more recent release?

**Comment by FroggyFlox** [comment]
@MikeMcPherson , 



> What's the best way to let people know that this Rock-on will only work on a version of Rockstor with Docker command argument support (looks like 3.9.2-39 or later to me)?

So far, I would say the best way is to state it in the `"description"` object of the json file. I believe we recently did the same thing for another rock-on I believe. You do bring up a very important point, however, and we could implement a way to automatically "disable" a rock-on for users who are running an incompatible version of Rockstor. We currently have a `"version"` object in the rock-on json files that we do not currently use so that could be an option to do so. For instance, we could use that field to define a minimum version of Rockstor required to run this rock-on and surface any incompatibility like that to the user in the webUI. What do you think?




> Any chance of updating the ISO to a more recent release?

Yes, @phillxnet has been hard at work on that very task. Your timing is actually really good as I can see that he just created the Rockstor-4.0.0-0 (https://github.com/rockstor/rockstor-core/releases/tag/4.0.0-0), so we're getting closer and closer.

**Comment by MikeMcPherson** [comment]
Yeah, I saw the 4.0 appear as I was submitting the PR this morning.  Congratulations!

I like the idea of having a minimum required Rockstor version in the Rock-on JSON.  I would be tempted to keep the current "version" to refer to the Rock-on and add a new optional object for the Rockstor required minimum version.  It looks like a few people are versioning their Rock-ons, and I see a couple of versions that look more like Rockstor releases.  Most just seem to be "1.0", though.  Having a Rock-on version probably isn't that useful.  I imagine once they are working they don't change much.

I guess that's a long way of saying I don't have a strong opinion one way or the other...  And should I edit in the addition to the description or will you do that?  I've never submitted a PR to anything before, so I don't want to mess up.  (I just use Github for my own projects.)

Thanks!  Mike

**Comment by FroggyFlox** [comment]
I agree with you with regards to the "version" object. I have to admit that I'm not sure what the original intent was with it, but I do believe it was meant to refer to the rock-on version indeed. 

> And should I edit in the addition to the description or will you do that? I've never submitted a PR to anything before, so I don't want to mess up. (I just use Github for my own projects.)

You can go ahead and include this in your PR once you submit it (I cannot see it yet). You can find instructions in our documentation if needed (link below). Of course, don't hesitate to ask here if anything's unclear.
http://rockstor.com/docs/contribute_rockons.html#contributing-a-rock-on

Sorry for the rather brief message; I'm short on time at the moment, but I hope I was still able to help.

**Comment by MikeMcPherson** [comment]
Thanks for the help.  This morning I followed the six steps at http://rockstor.com/docs/contribute_rockons.html.  I ended up with a PR in my own fork.  I just did it again following the directions at https://github.com/rockstor/rockon-registry/blob/master/README.md and I think it worked this time.

**Comment by MikeMcPherson** [comment]
If I did everything correctly, there should be pull requests pending for both the Rock-on and the write-up.  Please let me know if I've missed anything.
