### ISSUE TITLE
watchtower update needed

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockon-registry#233]
The watchtower rockon should point to https://hub.docker.com/r/containrrr/watchtower as the link has been updated for github and dockerhub.  It is the same image but we're pointing to a deprecated link.

**Comment by Hooverdan96** [comment]
I created a Pull Request for this - as suggested just replacing container and updating the description a bit. The official image also supports the ARM architecture.

**Comment by Hooverdan96** [comment]
@FroggyFlox. As discussed, following the new approach:
1. create pull request to introduce the official image of the Watchtower Rock-on - see above pull request #247 
2. subsequent pull request will deprecate the unmaintained version. I can link it to this issue, or create a separate one.

**Comment by FroggyFlox** [comment]
> subsequent pull request will deprecate the unmaintained version. I can link it to this issue, or create a separate one.

@Hooverdan96 , I just merged your PR #247 , so you can go ahead and take care of deprecating the now old "Watchtower" rock-on.

Cheers,
