### ISSUE TITLE
Sickrage image is deprecated

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#240]
The linuxserver/sickrage image we are currently using for the Sickrage rock-on is now listed as deprecated on its docker hub page and has not been updated for over a year. The docker hub page reads:

> Sickrage has been deprecated. Please use linuxserver/sickchill instead

Information on SickChill:
- Docker hub: [https://hub.docker.com/r/linuxserver/sickchill](https://hub.docker.com/r/linuxserver/sickchill)
- Image Github page: [https://github.com/linuxserver/docker-sickchill](https://github.com/linuxserver/docker-sickchill)
- SickChill Github page: [https://github.com/SickChill/SickChill](https://github.com/SickChill/SickChill)

We should thus either:
1. deprecate the Sickrage rock-on and replace it with a new SickChill rock-on.
2. deprecate the Sickrage rock-on without replacement.

Note that I do not know how much compatibility there is between Sickrage and SickChill but their Github documentation seems to imply a that SickChill could be a drop-in replacement for Sickrage.

**Comment by phillxnet** [comment]
@FroggyFlox Nice find.

I think I would favour 1 as it then provides continuity of existing function for our existing users. There are potential issues around such Rock-ons but these vary country to country and as we are global it's a local decisions of the user doing the install.

**Comment by Hooverdan96** [comment]
I second the option 1 proposal ... looks like there was a trademark/powerplay going on and sickrage apparently rebranded itself to sickchill, so I think the likelihood of it being a drop-in replacement is fairly high. Comparing the json file to the new Linuxserver.io image, it seems the only difference (addition) is the timezone mapping ... not sure whether the old image had that option as well, or "we don't care" and leave it out. Then it would be really only a drop-in (and maybe some update to the descriptions and more_info section to bring it up to the more recent documentation requirements.

Just for reference: link to a "not so subtle" article describing what went on about 2 years ago: https://torrentfreak.com/sickrage-rebrands-to-sickchill-to-avoid-trademark-war-181027/#:~:text=After%20a%20former%20developer%20applied,be%20known%20as%20'SickChill'.

**Comment by Hooverdan96** [comment]
@FroggyFlox - I created a pull request for adding the SickChill image - it pretty much dropped right in as a replacement, but I created a new json file and pepped up the descriptions/instructions.

**Comment by FroggyFlox** [comment]
@Hooverdan96 , as you probably saw already, I merged your PR #245 , so feel free to take care of deprecating the SickRage rock-on if you'd like to.
Of course, let me know if you can't and I'll take care of it.

Thanks again for all your help!
