### ISSUE TITLE
Sickbeard image seems unmaintained

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#241]
Similar to #240 , it appears that the Sickbeard image is not maintained anymore:
- the last update to the docker image was 3 years ago: https://hub.docker.com/r/linuxserver/sickbeard/tags
- the last commit on the github project page referred to by sickbeard.com dates from March 2016: https://github.com/midgetspy/Sick-Beard/

Given several other alternative projects exist, we probably should deprecate our Sickbeard rock-on.

**Comment by Hooverdan96** [comment]
I would agree, it looks like Sonarr is the "replacement" for this for which we already have a RockOn that's relevant.

**Comment by FroggyFlox** [comment]
Thanks for the information, @Hooverdan96 !

Let's go ahead and deprecate the Sickbeard rock-on in this case... feel free to go ahead and submit the PR if you feel like it ;) It should simply need to delete the .json file and remove its entry in `root.json`. You can have a look at #200 if you want.

Let me know if you don't have time or interest in it and I'll take care of it. No rush, of course ;)

Thanks
