### ISSUE TITLE
Remove deprecated image: TFTP-server?

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#257]
Our TFTP-server rock-on uses an image that was last updated 4 years ago. Would anyone have confirmation whether or not this image still works?

I believe the netboot.xyz proposed in #234 includes a tftp server so it could potentially be used as an alternative once merged.

**Comment by Hooverdan96** [comment]
Here could be an alternative, that has been updated a few times - and if the container is rebuilt occasionally, then the latest version of tftp-hpa will be pulled.
https://hub.docker.com/r/3x3cut0r/tftpd-hpa
and the documentation here (the github repo seems to be relatively active)
https://github.com/3x3cut0r/docker/tree/main/tftpd-hpa

The last tftp-hpa package update was in May-2020, so the image used for the Rockon is possibly missing some security fixes. So, either remove or replace with a different image (i.e. new Rockon and deprecate old one).
