### ISSUE TITLE
Consider removing deprecated image: linuxserver/hydra

### ISSUE THREAD

**Issue by thedrjones** [rockstor/rockon-registry#273]
The linuxserver/hydra image is now deprecated; the docker hub page reads (in the Application Setup section):

    THIS IMAGE HAS BEEN DEPRECATED. 
    Please use linuxserver/nzbhydra2 instead.

It recommends the updated NZBHydra2 instead, there is an older version of this available to migrate old V1 data, but latest image does not support this migration on newer versions, so users probably need to use this in parallel until new their NZBHydra2 configuration is manually built. 

Updated NZBHydra2 image has been submitted on PR https://github.com/rockstor/rockon-registry/pull/272

**Comment by FroggyFlox** [comment]
@thedrjones ,

Noting here for reference that now that your PR #272 has been merged, we should address this one in the near future.
