### ISSUE TITLE
Support for port ranges

### ISSUE THREAD

**Issue by jurijzahn8019** [rockstor/rockon-registry#288]
Hi,

is there a way to support port ranges in port definitions?

as required here https://hub.docker.com/r/doitandbedone/ispyagentdvr container want map port range `50000-50010/udp`

But at the moment there is no way but to hardcode this in the "container.opts"

thanks in advance

**Comment by phillxnet** [comment]
@jurijzahn8019 This question would be better posed on our forum:

https://forum.rockstor.com/

All our currently active developers as also forum members. Plus there are now quite a few forum members who have also contributed or helped with contributing new rock-ons.

Thanks.

**Comment by jurijzahn8019** [comment]
Ok, cool

**Comment by phillxnet** [comment]
@jurijzahn8019 It may be that we have some improvements to be made in this area (most likely) and in which case these can be discussed first on the forum and then a focused GitHub issue can be created for that improvement. And given this repo is just the Rock-on definitions the the likely location for an improvement in how the Rock-on definitions are processed would be our:
https://github.com/rockstor/rockstor-core
repo. But we would likely want to also extend the Readme in this repo also as it contains the canonical 'guide' to writing a Rock-on. But we also have the following doc section that is related:
Contributing a Rock-on: https://rockstor.com/docs/contribute/contribute_rockons.html

Hope that helps.
