### ISSUE TITLE
Update Bitwarden_rs refernces to Vaultwarden

### ISSUE THREAD

**Issue by RlndVt** [rockstor/rockon-registry#296]
The Bitwarden_rs project has been renamed to Vaultwarden. References and links to said project need to be updated.

**Comment by phillxnet** [comment]
@RlndVt Thanks for creating this issue and stepping up to the task. Much appreciated.

Linking to your sister issue in the rockstor-docs repository:
https://github.com/rockstor/rockstor-doc/issues/318
