### ISSUE TITLE
Pi-hole not exposing DHCP server ports

### ISSUE THREAD

**Issue by Bruffandino** [rockstor/rockon-registry#305]
Pi-hole's DHCP server option is not working, I believe because the DHCP server port (68) is not exposed.

**Comment by Hooverdan96** [comment]
Could it be that you meant port 67/udp instead? According to the container documentation:
https://hub.docker.com/r/pihole/pihole and the wiki https://docs.pi-hole.net/docker/DHCP/

it seems that it requires port 67, not 68.

In any case, neither of these ports are exposed in the rockon at this time, you are correct.

If you want to test it, you could add another port to a copy of the corresponding json file and add the port 67 in this area:

https://github.com/rockstor/rockon-registry/blob/0c674aecef6e3177cc0028d88cf3b02a36f771c3/pi-hole.json#L25

If that resolves the issue, would you want to submit a pull request for the update of the rock json file?

**Comment by Bruffandino** [comment]
You are correct, it's port 67 indeed. That's not enough though, also the container's network mode needs to be changed in order for the DHCP server to be correctly exposed to the local network, as explained in the PI-Hole wiki. There are many options there, I'm not sure which one would better suit better a generic Rockstor installation.

I managed to make it work using --net=host mode, and specifiying Pi-hole's web server port through the WEB_PORT variable to something different from port 80 (which is taken by Rockstor's gui). I had to specify the network adapter name as well, which  is different from the default "eth0"

**Comment by Hooverdan96** [comment]
Further discussions by Forum User Felix further support the move to using `net=host` to simplify the dhcp server option that pi-hole offers:

https://forum.rockstor.com/t/setting-up-pi-hole/8705

**Comment by FroggyFlox** [comment]
Thank you so much for your diligence in checking first, @Hooverdan96 !

@Bruffandino, my sincere apologies for such a delay in getting to your request. It was a rather important issue so thanks to @Hooverdan96 and @phillxnet it should be implemented rather soon. Keep an eye on #342 as that should resolve it. Let us know whether that indeed fixes your original problem once it is published.
