### ISSUE TITLE
haproxy-letsencrypt image not available anymore

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#311]
The docker image

`illi/docker-haproxy-letsencrypt` is not on docker hub anymore.
The `https://github.com/daniel-illi/docker-haproxy-letsencrypt/tree/rock-on` repo is still there (last updated 6 years ago), but the owner is not hosting it on docker hub anymore. And the original repo it was forked from has also not been active in a number of years.

This Rockon should be deprecated and replaced with an active version. Not sure, whether anybody is currently actively using it and might be interested in creating a new version of this.

Suggestion is to remove this Rockon, as it doesn't work at all. And hope for the best that somebody takes up the challenge to create a replacement.

**Comment by phillxnet** [comment]
@Hooverdan96 
Re:
> Suggestion is to remove this Rockon, as it doesn't work at all.

Agreed.
