### ISSUE TITLE
owncloud-official.json and owncloudHTTPS.json should be updated/deprecated

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#313]
the official https://hub.docker.com/_/owncloud image used in both those Rockons has a deprecation notice on the web page (not been updated since December 2018), referring users to the https://hub.docker.com/r/owncloud/server/ image.

Probably deprecate those two and create a new one using the new official image by owncloud itself

**Comment by phillxnet** [comment]
@Hooverdan96 @FroggyFlox I think we have some history of an attempt to do this by @ahlongas07  here:
https://github.com/rockstor/rockon-registry/pull/293

Linking for context in case it helps. See @ahlongas07's comment here:
https://github.com/rockstor/rockon-registry/pull/293#issuecomment-978146320
