### ISSUE TITLE
Rockon Postgres Versions stale?

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#314]
The underlying images for the two dedicated Postgres Rockons have not been updated/pushed in quite some time:
postgres-10.6.json last update over 3 years ago
postgres-9.5.json last updated over 2 years ago

Does this pose a security risk, etc.? Should we replace these with a much more recent version? Comes back to another conversation on surfacing the tags in the Rockon configuration, so we don't have to manage version-specific Rockons for things like DBMS as they are bound to change over time.

**Comment by phillxnet** [comment]
@Hooverdan96 Good point. But if I remember correctly they were required at the time as they behave quite differently. If we could find newer images that would be good.

**Comment by Hooverdan96** [comment]
This would require to move from official to custom, which is probably ok.
