### ISSUE TITLE
Xeoma image stale?

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#318]
The images user for xeoma.json was last updated 2 years ago. Is there one that could be used in its place that's more active?

**Comment by phillxnet** [comment]
@Hooverdan96 I've no idea on this one actually. We could ask on the forum if there are any suggestions. We could drop it if there are no takers as if no one is bothered then we might as well not carry it.

I quite keen on dropping unmaintained images as as are in the 80's for our Rock-ons count and they are meant to be curated 'picks' so your recent issues focusing on this is great. Thanks for highlighting all these older unmaintained images.

**Comment by Hooverdan96** [comment]
@mattwire, are you still using that Rockon? If so, any suggestions on how what a newer/more active version would be that could be useful for our Rockon?

**Comment by mattwire** [comment]
@Hooverdan96 sorry have not used for a long time now
