### ISSUE TITLE
Remove Bitcoin Rock-on

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#349]
The time has passed for this Rock-on. By way of updating, and refining, our Rock-on selection it has been ear-marked for removal.

**Comment by StephenBrown2** [comment]
> The time has passed for this Rock-on.

Huh? What has passed? I was just looking to install this as I'd like to be self-sovereign, but found it had been removed. The docker image By [kylemanna](https://hub.docker.com/u/kylemanna) was updated a month ago, so it's clearly still in development.
