### ISSUE TITLE
The image for Owncloud is no longer maintained

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#357]
The owncloud image we are using for the owncloud Rock-On is now 4 years old and seemingly no longer maintained: the GitHub repo is now archived: https://github.com/pschmitt/docker-owncloud

We should thus deprecate that Rock-On.
If interest in a new owncloud Rock-On is expressed by the community, then we can recreate one with a more appropriate image.

**Comment by phillxnet** [comment]
@FroggyFlox Agreed, lets delete it and react quickly to community contributions/interest for a replacement: if found.
