### ISSUE TITLE
CouchPotato repository not maintained anymore

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#368]
The CouchPotato development has not been maintained for quite some time (https://couchpota.to/) and the github repo has been archived since September 2021. The corresponding linuxserver.io image has also not been updated in two years and carries a deprecation notice, too.

I suggest, that we remove this from the Rockon repository, as the recommended alternative, Radarr, is already part of the offerings here.

**Comment by phillxnet** [comment]
@Hooverdan96 Agreed, thanks for submitting this issue. We should definitely drop any-all Rock-ons with unmaintained images. Folks can always pull older definitions from GitHub history and re-instate via custom if they absolutely depend on them.
