### ISSUE TITLE
LMS / mysqeezebox.com question

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#375]
@Hooverdan96 is LMS now defunct given the demise of  https://mysqueezebox.com?

---

"Logitech Media Server (Squeezebox), move to latest release tag": https://github.com/rockstor/rockon-registry/pull/283

**Comment by Hooverdan96** [comment]
No, LMS does not require squeezebox and its web services, so as long as the repo is still maintained it will still be valid.
Will need to adjust the documentation of the Rockon a bit. I use the picoreplayer to stream from LMS and that still works perfectly fine.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks.
