### ISSUE TITLE
Calibre

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#386]
It is proposed that we add the Open Source go-to for ebooks managmenet: Calibre. One of our preferred container authors linuxserver.io, a fellow Open Collective (https://opencollective.com/linuxserver) have the following available:

## Calibre ebook management

- https://calibre-ebook.com/

## docker image info
Linuxserver.io offer a -web variant of existing Calibre databases, and a full Calibre with a Web-UI capability:
- GitHub: https://github.com/linuxserver/docker-calibre-web
- DockerHub Calibre-web: https://hub.docker.com/r/linuxserver/calibre-web
- DockerHub Calibre: https://hub.docker.com/r/linuxserver/calibre
This image sets up the calibre desktop app and makes its interface available via KasmVNC server in the browser. The interface is available at http://your-ip:8080 or https://your-ip:8181.

### docker-mods:
https://mods.linuxserver.io/?mod=calibre-web
- https://github.com/linuxserver/docker-mods/tree/universal-calibre
- https://github.com/linuxserver/docker-mods/tree/calibre-web-dtrpg-metadata
- https://github.com/linuxserver/docker-mods/tree/calibre-web-kcc

Where the `latest` [tag variant](https://docs.linuxserver.io/images/docker-calibre/#version-tags) looks to be multi-arch re amd64 & arm64.

**Comment by Hooverdan96** [comment]
@phillxnet I created a simplistic calibre json (leaving out the mod for non-latin language and GPU stuff). That seems to work. Trying to hide the Docker mod, font package load inside the `opts` section did not go well, not sure why, one of the setting took and the other got bungled during the building of the docker command. I originally planned to only expose the LC_ALL variable where one could set the language for the application. That might be overkill, not sure.

the non-web calibre comes with a simple web access built-in. We also have the COPS Rockon to ties into the Calibre database (I found though that after the first COPS start the path has to be adjusted inside the php.ini to find the database file it's looking for.

I have not attempted to implement the calibre-web one - was also not sure whether you saw this is a multi-container Rockon (calibre plus calibre-web) or resulting in 2 separate Rockons. Calibre-web relies on the calibre database, it cannot create one (I've seen scenarios where people rsync from the desktop and effectively have 2 databases on 2 different servers and run the desktop version on one and the web view on another).

I assume, since we also have COPS that it would make the most sense to separate that into two Rockons, and maybe also update the COPS description to indicate my finding above about the path.

**Comment by Hooverdan96** [comment]
@FroggyFlox, question for you:

when I did try to introduce additional parameters I first added `-e` into the `opts` section, in different variations. That cause some of the environment variable value assignments to be truncated in the resulting docker command. I then explicitly (i.e. visible in the Rockon config wizard), but 2 out of three showed the same symptom. Any idea what might be causing this?

the Rockon docker command looked like this (erroring out):
```
cmd = /usr/bin/docker run -d --restart=unless-stopped --name calibreserver -v /mnt2/lms-playlist:/books -v /mnt2/test-config:/config -v /etc/localtime:/etc/localtime:ro -p 8081:8081/tcp -p 8090:8096/tcp -e DOCKER_MODS linuxserver/mods:universal-package-install - e f o -e PUID=1001 -e PGID=1001 -e LC_ALL=us_en.utf8 linuxserver/calibre:latest
```
This portion `- e f o`  looks non-sensical. The json file portion looked like this:

```
                    },
                    "DOCKER_MODS": {
                        "description": "(Optional) If Calibre should be started in a non-Latin character language (Chinese, Japanese, Korean, etc.), then activate this mod by entering \"linuxserver/mods:universal-package-install\". Otherwise, just enter \"null\"",
                        "label": "Docker Mods",
                        "index": 3,
                        "default":"linuxserver/mods:universal-package-install"
                    },
                    "INSTALL_PACKAGES": {
                        "description": "Enter \"fonts-noto-cjk\" to load non-Latin fonts. If you populated the above setting with \"null\" do the same here.",
                        "label": "Docker Mod-install font packages",
                        "index": 4,
                        "default":"fonts-noto-cjk"
                    },
                    "LC_ALL": {
                        "description": "start Calibre in a language different than default English, using utf8 (e.g. zh_CN.UTF-8). If you populated the above setting with \"null\" do the same here.",
                        "label": "Language installs",
                        "index": 5,
                        "default": "en_US.UTF8"
```
as one can see, the first out of that is parsed almost correctly into the command string (it seems to be missing the `=` sign), but the 2 subsequent ones are not at all. What am I missing? The same happened when I placed these explicitly into the `opts` section as three separate environment settings. I did run JSON linting and all that, so I don't think I'm missing a `,` or brackets anywhere. Only thing I can think of is that the `/` and `:` in the `DOCKER_MODS` variable does something weird to the parsing piece.

I can open a separate issue in the rockstor-core repo for this, too, if there is no simple explanation.

**Comment by FroggyFlox** [comment]
Interesting.
If you haven't already, could you try without the double quotes (`"`) inside the values (and thus without the backslashes `\` too)? Maybe keep these values as simple as possible for now with just dummy text to see where it comes from.



> Only thing I can think of is that the `/` and `:` in the `DOCKER_MODS` variable does something weird to the parsing piece.

I thought that too but then it seems that this value is correctly parsed from trading the docker run command.

If the above doesn't work, what I usually do in these cases is starting from no env variable, then increase the complexity progressively to see where it starts to fail: no env first, then one of the env but with simple values, then the env with the complex value, etc...

Alternatively, you could have a look at what is in the database itself using `psql` to see how Rockstor parsed your JSON even before you run the Rock-on install wizard.

Sorry I can't seem to be of more help for now.

**Comment by Hooverdan96** [comment]
I will try the single quote piece. However, when I had this in the `opts` section then there was no description that could get in the way, and the outcome was the same.

I will also check 'psql'

**Comment by FroggyFlox** [comment]
Good point... Sorry I forgot you detailed that. Hopefully trying the env one at a time will help pinpoint the culprit, then.

**Comment by Hooverdan96** [comment]
alright, those escaped double quotes might have been it. It works now. I moved a couple of environment variables back into opts, so the user doesn't have to set them. I will start a pull request shortly.
