### ISSUE TITLE
duplicati Rockon Environment Variables

### ISSUE THREAD

**Issue by BrokenOnedroid** [rockstor/rockon-registry#404]
Hi,
I tried installing the duplicati Rockon.
The webui was not reachable.
I did one test and my result was that `SETTINGS_ENCRYPTION_KEY` env var needs to be added.
See: https://docs.linuxserver.io/images/docker-duplicati/
Without it the container did not start correctly.

**Comment by Hooverdan96** [comment]
You might very well be right. This Rockon has not seen any major updates in the last five years, bar some adjustment on descriptions, if I see that correctly. I suspect there have been some breaking changes in between the duplicati versions that would require additional/different parameters for it to work.

**Comment by Hooverdan96** [comment]
Looks like this was the breaking change, just a couple of months ago.

https://github.com/duplicati/duplicati/pull/5472

**Comment by BrokenOnedroid** [comment]
Yeah that looks like that was the change.

**Comment by BrokenOnedroid** [comment]
Just found this: 
duplicati/duplicati#5496

I'm going to set `DUPLICATI__DISABLE_DB_ENCRYPTION=true` and check if that makes it possible to start the container without setting the `SETTINGS_ENCRYPTION_KEY`.

**Comment by BrokenOnedroid** [comment]
So linuxserver/duplicati does not support ` DUPLICATI__DISABLE_DB_ENCRYPTION=true` .
duplicati/duplicati does.
