### ISSUE TITLE
Provide a Nextcloud rock-on

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#43]
There doesn't yet appear to be an official one:
https://github.com/nextcloud/server/issues/145
But we could use greyltc's
https://github.com/greyltc/docker-nextcloud
which is tagged (defaults to latest = latest stable release):
https://help.nextcloud.com/t/docker-image-available/351/19
Note that config, apps, data, sslcert volume maping setting could be taken from: @nrgeen 's suggestion in the following issue on GitHub for this docker container:
https://github.com/greyltc/docker-nextcloud/issues/4

-v /volume/nextcloud_docker/config:/usr/share/webapps/nextcloud/config
-v /volume/nextcloud/apps:/usr/share/webapps/nextcloud/apps 
-v /volume/nextcloud/data:/usr/share/webapps/nextcloud/data
-v /volume/nextcloud/sslCert:/root/sslKeys

**Comment by phillxnet** [comment]
Maybe it would be best to model this as closely as possible on our existing owncloud rock-on so that any transition from one to the other can be as smooth as possible.

**Comment by daniel-illi** [comment]
This one is on the way to become the official nextcloud docker image:
https://github.com/nextcloud/docker
https://hub.docker.com/r/indiehosters/nextcloud/

See comment https://help.nextcloud.com/t/docker-image-available/351/50 and following

**Comment by daniel-illi** [comment]
Since my last comment an official docker image has appeared: https://hub.docker.com/_/nextcloud/

**Comment by phillxnet** [comment]
@daniel-illi That's great news, we might want to keep an eye on the docker version compatibility though, from your supplied link we have:

"Supported Docker versions
This image is officially supported on Docker version 1.12.6.

Support for older versions (down to 1.6) is provided on a best-effort basis."

Currently we have:
```
docker --version
Docker version 1.9.1, build a34a1d5
```

**Comment by JohnnyCalavera** [comment]
Suman stated that 3.8.16-15 comes with updated docker packages (1.13.1). 
So I guess we'll have a few more rock-ons coming to Rockstor 3.9

**Comment by phillxnet** [comment]
Please update the following forum thread where forum use OpenSourceUser expressed an interest in this Rockon:
https://forum.rockstor.com/t/linuxserver-ios-nextcloud/3101

**Comment by martmaiste** [comment]
Here is another Nextcloud Docker and Rock-On file for easy installation. It includes php-fpm and Nginx reverse proxy with SSL and Let's Encrypt support.

https://github.com/martmaiste/rockstor/tree/master/nextcloud

**Comment by florianduclot** [comment]
> Here is another Nextcloud Docker and Rock-On file for easy installation. It includes php-fpm and Nginx reverse proxy with SSL and Let's Encrypt support.
https://github.com/martmaiste/rockstor/tree/master/nextcloud

I tried this container on Rockstor 3.9.0 and it seems to work for me... a JSON file already exists, and the inclusion of a reverse proxy in the container is appreciated (to me, at least).

**Comment by bennysp** [comment]
FYI - I have submitted a PR for a **nextcloud-official** which was modeled from the **owncloud-official**.  I have also tested this and I am using it.

[https://github.com/rockstor/rockon-registry/pull/145](https://github.com/rockstor/rockon-registry/pull/145)

**Comment by phillxnet** [comment]
I have updated @bennysp pr referenced in this issue as there is some useful discussion which I think is on verge of being resolved, i.e. I think we are almost there on this one. Please take a look at that pr and comment as you see fit.

**Comment by phillxnet** [comment]
Update: @bennysp pr has now been merged but we are awaiting further changes prior to it being added to root.json and published. Please update this issue accordingly with these pending changes.
@FroggyFlox I'm hoping you can finally close this issue via said proposed changes which, due delays on my part, we were unable to have @bennysp commit for themselves.
