### ISSUE TITLE
Create a Zoneminder plugin

### ISSUE THREAD

**Issue by zorrobyte** [rockstor/rockon-registry#44]
After purchasing several IP cameras and running Synology's Surveillance Add-on, I'd like to bring some sort of IP Camera DVR to Rockstor. Zoneminder is a free and open source solution for this. I'll see what I can write up, pending a successful Rockstor install.

**Comment by phillxnet** [comment]
@zorrobyte This would be great, but last I looked although there was an official zoneminder docker image it wasn't fully tested. So at least back then it was early days. Thanks for you efforts on this one.
Linking to a prior mention / request (by me actually) and seconded by another entry in the forum:
https://forum.rockstor.com/t/rock-on-requests/41/50

And linking to the official docker hub image for convenience:
https://hub.docker.com/r/kylejohnson/zoneminder/
N.B. Under the Docker subheading there they have:
"ZoneMinder, and the ZM webserver, will run using the Dockerfile contained in this repository. However, there is still work needed to ensure that the main ZM features work properly and are documented."
It may be that only locally connected devices are compromised and IP cameras may well work. If that is the case it could be included as a caveat in the Rock-on user facing info.

And their main GitHub page:
https://github.com/ZoneMinder/ZoneMinder

**Comment by phillxnet** [comment]
Linking to another forum post mentioning zoneminder as a request:
https://forum.rockstor.com/t/new-user-migrating-from-freenas/1583

**Comment by magicalyak** [comment]
Does this still need to be done? I can try to take a crack at it?

**Comment by phillxnet** [comment]
@magicalyak Not as far as I'm aware. @zorrobyte showed interest earlier on but I haven't seen any commits against the issue. Thanks for stepping up. I did look the other day on docker hub and there does appear to be a good few images, I think it would be best if we could use the official one as I indicated earlier though. If it works that is. If you make any progress do please note it here in case anyone else wants to pick up where you left off. Unless of course you manage to sort it.

Thanks.

I see you have already put in a pr for PocketMine / Minecraft server; nice idea.

**Comment by magicalyak** [comment]
Let me see what I can do, this shouldn't be too difficult and I do feel a lot more confident after getting pocketmine to work (it had a LOT of quirks and no one else had it working on the new API).

**Comment by magicalyak** [comment]
It's pending a pull request
[https://github.com/rockstor/rockon-registry/pull/50](url)

**Comment by magicalyak** [comment]
The official zoneminder isn't a good fit, I adapted a VERY popular one that is used on unraid to work on rockstor.  One big caveat is that it runs with --privileged flag on because it needs to set the shm to 4096M.  If we can use a new version of docker, we can easily pass a runtime flag for this without using privileged.  privileged also allows any cameras physically attached to the system.  

Main difference between zoneminder official and what i used is that I am using the repo version through phusion/baseimage (similar to ubuntu) while the official would rebuilt zoneminder (which is too bleeding edge I think).  the issue above is present in both.

**Comment by magicalyak** [comment]
All config and data should be in the /config
[https://github.com/aptalca/docker-zoneminder/blob/v1.29/README.md](url)
> All settings and library files are stored outside of the container and they are preserved when this docker is updated or re-installed (change the variable "/path/to/config" in the run command to a location of your choice)

Ok so no sense making a new directory, it would have to be mounted inside the root anyway (due to zoneminder's workings).

Inside my /config I have 3 directories (data,mysql,perl5)
inside data i have (events, images, temp)

so it's an all in one.  I know splitting it is the norm but I'd have to fork and rewrite this to do so.
All the data will persist though!

**Comment by magicalyak** [comment]
@phillxnet this version lets you use mp4, it's in the more_info and also in the developer link on the README.  👍

**Comment by phillxnet** [comment]
@zorrobyte as @magicalyak has now submitted and had accepted a Zoneminder Rock-on I hope you are now OK with this issue being closed, don't be surprised if @schakrava closes this by way of cleaning up but you are also able to close it given you opened it, you can always re-open if you thing it's in error or if @magicalyak json doesn't address a specific need you had.
Thanks.

**Comment by magicalyak** [comment]
Zoneminder is now live and I just noticed 1.30 is out!!! I'll update it accordingly, I don't think there is a way to automate the updates just yet but perhaps 1.30 will let me.  In any case 1.29 works great and has the new encoding features.

**Comment by phillxnet** [comment]
@magicalyak Maybe this update could be done under a different issue to track particulars there. By the way I've done a docs pr for the ZoneMinder Rockon install as thought it worth having it's own.
https://github.com/rockstor/rockstor-doc/pull/154
I'll keep an eye on your comments re the 1.30 version and try and update the doc accordingly if need be.

**Comment by zorrobyte** [comment]
No worries @phillxnet - I've been tied up with work. I am very proud of the Rockstor community, you all rock!

**Comment by phillxnet** [comment]
@zorrobyte Thanks. Feel free to close this issue at your leisure as I suspect it will be better to start a fresh issue for any pending updates or the like.
Cheers.

**Comment by phillxnet** [comment]
Fixed by @magicalyak in pr #50 
Thanks everyone.
