### ISSUE TITLE
Create SpiderOak Rockon

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockon-registry#54]
https://forum.rockstor.com/t/spideroak-rockon/1136

I can likely do this but wanted it tracked here.  SpiderOak is used to sync and backup files and can run in headless mode, making it ideal for use on RockStor.  I know a lot of people use it at work so this is just a request for it to be added.

**Comment by phillxnet** [comment]
@magicalyak Good idea.

**Comment by magicalyak** [comment]
This guy has a github but I don't like the dockerfile, it's too inefficient in my mind so I'll likely rewrite.  Just posting here as a notepad
https://github.com/neochrome/docker-spideroak

**Comment by phillxnet** [comment]
Are there any takers on this one. I see SpiderOak as a nice Rock-on addition.

**Comment by phillxnet** [comment]
@magicalyak I'm assuming things must have moved on by now. Is their now an official SpiderOak docker image?

**Comment by magicalyak** [comment]
No there isn't but there may be a better one, this one hasn't been updated in years so let's close this one out

**Comment by phillxnet** [comment]
@magicalyak Closing as per suggestion. We can always re-open or start a fresh issue on the same it if comes to that.
