### ISSUE TITLE
Symform is dead - remove symform Rockon?

### ISSUE THREAD

**Issue by StephenBrown2** [rockstor/rockon-registry#56]
From http://symform.com/:

> It has been a blast, but all good things must come to an end.
> 
> We started the Symform service in 2009 with the idea of creating the worlds largest cloud storage without the data centers. We reached an amazing point in which we were managing petabytes of storage and billions of data objects across 170 countries. Symform was eventually acquired and became part of the team at Quantum. **Unfortunately as of July 31, 2016 Symform has shut down operations and will no longer be available for use.** From the bottom of our hearts, we want to thank all of you for your support and belief in what Symform accomplished.

Not sure what Symform was, but apparently it is no more.

**Comment by alazare619** [comment]
please close this ticket as the json file was removed.
