### ISSUE TITLE
improve zoneminder volume labeling

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#64]
When installing zoneminder rock-on the user is asked to provide "Config Storage" but the tooltip more accurately portrays this as data and config storage. Would be nicer to have:
"Config Storage"
label changed to
"Data and Config Storage"
Minor but worth doing for first time interpretation.

**Comment by magicalyak** [comment]
Is the best way to do this to open a new PR?

**Comment by magicalyak** [comment]
It appears that data isn't stored in the right place in 1.30 I am working on that issue hopefully this week

**Comment by phillxnet** [comment]
@magicalyak Does your point only relate to the 1.30 Rock-on? In which case we could still fix this in the other zoneminder Rock-on. But yes would be nice to tend to them both really.

**Comment by magicalyak** [comment]
I believe that's 1.30+, so later versions also.

**Comment by phillxnet** [comment]
Closing as relevant rock-on has now been removed in #300
