### ISSUE TITLE
unifi rockon missing log volume?

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockon-registry#85]
Upstream has two volumes, one for config, one for logs. Could we get prompted for the logs volume too?

**Comment by phillxnet** [comment]
Linking to upstream dockerhub image page:
https://hub.docker.com/r/jacobalberty/unifi/

```
docker run --rm --net=host -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5
```

**Comment by roweryan** [comment]
But the rockon doesn't support the timezone or both volumes :(
