### ISSUE TITLE
subsonic rockon fails to install

### ISSUE THREAD

**Issue by brodonalds** [rockstor/rockon-registry#90]
Hey all, I'm getting an error when i attempt to install the subsonic rockon. I get a message about it being unable to find the docker image even after updating.

**Comment by JasonTarka** [comment]
I didn't notice there was a bug report filed for this, but I fixed it in #103, which got merged earlier today.

**Comment by phillxnet** [comment]
@brodonalds If you could confirm that your install now works (after pressing the Update button on the Rock-ons page that is) then you could close this issue as:
"Fixed by @JasonTarka in pr #103 ".

**Comment by brodonalds** [comment]
Looks good guys. Thanks
