### ISSUE TITLE
Add a bacula server rockon

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#93]
Bacula is a well respected highly developed client server network backup system. Running a server (Director service + Storage Daemon) instance as a Rockon would add value to Rockstor. Client software is available for all major platforms and the project has now been running for 17 years.  Although tape archive facilities were it's original remit it now equally supports file archives via pools of backup volumes where the pool defines it's volume members characteristics.
Main page:
http://blog.bacula.org/
Git repo:
http://www.bacula.org/git/
Licence appears to be AGPLv3: http://blog.bacula.org/what-is-bacula/bacula-copyright-trademark-and-licenses/
Manuals: http://blog.bacula.org/documentation/documentation/

Configuration can be  achieved via the Baculum Web GUI Tool (Bacula version >= 7.0):
http://www.bacula.org/7.4.x-manuals/en/console/Baculum_Web_GUI_Tool.html
screen shots:
http://www.bacula.org/7.4.x-manuals/en/console/Baculum_Web_GUI_Tool.html#SECTION00370000000000000000
or via console access via bconsole.

Their is utility in separate Director and Storage Daemon Rockons, however it might also be nice to have a 'one stop shop' for the server components to aid ease of setup. Leaving only client software install to complete a full network backup solution. This would then serving both ends of the scale for such things.

I propose the following Rockons:

Bacula Storage Daemon (bare bones for use with existing Bacula setups)
Bacula AIO (Director + Storage + Catalog (PostgreSQL based))

Bacula components:
http://www.bacula.org/7.4.x-manuals/en/main/What_is_Bacula.html#SECTION00220000000000000000

From a quick look on https://hub.docker.com/ I don't see any well documented and maintained examples, however there is:
https://github.com/RedCoolBeans/docker-bacula-opensource
where each element is defined in a separate docker image and we could in turn build our Rockon using  these images akin to our existing owncloud and rocketchat Rockons. But these images are now 10 month old with 6 releases since then.

Ready for comment / advise as my own familiarity with Bacula is rather ancient, ending around 2010 when I last recommended it in a commissioned configuration proposal.

**Comment by schakrava** [comment]
I've used Bacula a few years ago and remember liking it. I agree with you @phillxnet that it would be great to have it as a Rock-on.

**Comment by pauldsmyth** [comment]
I used to use Bacula but then moved to Bareos which is a fork by one of the founders. I'm not currently using it but would be interested in this

**Comment by alazare619** [comment]
https://hub.docker.com/r/freenas/bacula/
also exists

**Comment by phillxnet** [comment]
@alazare619  Yes I saw that image, by far the most downloaded.
Appears to build from source version 741. Not sure that's the way to go really.
And 741 (1st June 2016) is now 5 releases behind current of 7.4.6 (11th March 2017).
Tricky. Looks like we may have to role our own maybe.
My fedora 24 has 7.4.5-1 packages available by default.

My understanding is that one has to keep the client and server packages in step, but for windows client versions that hasn't matter for the last couple of versions, hence 7.4.4 client versions on Bacula's main page:
http://blog.bacula.org/
However an Ubuntu 14.04.5 system here only lists version 5.2.6 which is very very old.
Also there are only Windows binary downloads on their page!!!

I'm rather favouring we adopt @pauldsmyth move and consider Bareos given they have a far more current binary download for a bunch of linux distros and win.

Also from their web page:

"Bareos is a 100% open source fork of the backup project from bacula.org. The fork is in development since late 2010, it has a lot of new features.
The source has been published on github, licensed AGPLv3."

"Backup Archiving Recovery Open Sourced"
https://github.com/bareos/

see also:
https://www.bareos.org/en/
https://www.bareos.org/en/download.html

Plus there are up to date (by major version number) BareOS (16.2) docker images for all components with excellent (rather than no) documentation by barcus on dockerhub:

https://hub.docker.com/u/barcus/

On the grounds that bacula would in comparison appear almost abandoned from the client binary point of view and has very few docker image optins I'm changing this Issue to BareOS from Bacula:

@pauldsmyth Could you explain why you made the change?
@schakrava Looks to me like bareos is going to be a better fit with Rockstor. Especially given client availability.

As I say my bacula knowledge is pretty ancient but the fact that there are very few commonly used docker images is rather telling.

**Comment by phillxnet** [comment]
In order that this issue be available for those those wishing to develop a bacula rockon I'll open a new issue for BareOS.

**Comment by alazare619** [comment]
I've done some reading over my lunch break. I to favor the idea of BareOS based upon what I've read.

**Comment by phillxnet** [comment]
Linking back to #94 "Add a BareOS server rockon".

**Comment by phillxnet** [comment]
This issue and it's sister BareOS proposal have had not further attention. Closing in favour of focusing on the seemingly more natural fit of BareOS.
