### ISSUE TITLE
More descriptive Rockon Catalog

### ISSUE THREAD

**Issue by seffyroff** [rockstor/rockon-registry#96]
Right now browsing the Catalog of Rockons is very sparse.  I don't know the source of the Rockon (whose Plex comtainer is that) without looking in Github at the contents of the .json.  I don't know the version number, or last update version - these are important :)

**Comment by phillxnet** [comment]
@seffyroff Sorry to wake this sleeping issue up but it's a really good point.
Linking to a related issue re standardising links within the individual Rock-on presentations:

"Make Rock-on links consistent" #31

To centralise this discussion I'm going to close this issue as a duplicate and quote your comment in that issue. We are then more likely to keep this issue focused.

Duplicate of #31
